spring.application.name=operation

spring.datasource.url=jdbc:postgresql://localhost:5050/spiro_records_db
spring.datasource.username=spiro_user
spring.datasource.password=spiro123
spring.datasource.driver-class-name=org.postgresql.Driver


